In [1]:
import torch
import torch.nn as nn

In [2]:
from recurrent_norm import RecurrentNorm2d

In [3]:

timesteps = 20
rn = RecurrentNorm2d(128, timesteps)


# timesteps, batch size, channels, h, w
input_seq = torch.randn(timesteps, 5, 128, 64, 64)

print("THESE VALUES SHOULD BE THE SAME")
for i, input_ in enumerate(input_seq):
    # should get the same values here
    print(rn(input_seq[0], i)[0, 0, 0])

print("=" * 100)
l1_loss = nn.L1Loss()
pred = 0
for i, input_ in enumerate(input_seq):
    pred += torch.sum(rn(input_, i))
out = l1_loss(10, pred)
out.backward()
print("=" * 100)
    
print("THESE VALUES SHOULD BE DIFFERENT")
for i, input_ in enumerate(input_seq):
    # should get different values here
    print(rn(input_seq[0], i)[0, 0, 0])


THESE VALUES SHOULD BE THE SAME
tensor([-0.1370, -0.4188, -0.4459,  0.0483,  0.6758,  0.2776, -0.3167,  0.6235,
        -0.4281,  0.4090, -0.4585,  0.6400,  0.0375,  0.1952, -0.2011, -0.3472,
        -0.2236, -0.3259,  0.5152, -0.2563, -0.0222, -0.3384, -0.3476, -0.2251,
         0.1043,  0.1380,  0.0514, -0.5662,  0.5090, -1.0926,  0.3040,  1.4066,
         0.1902,  0.3010, -0.9314,  0.3816, -0.0229, -0.5982,  0.5892,  0.1747,
         0.0237,  0.7334,  0.6304, -0.8470,  0.6093, -0.7605,  0.3215,  0.2205,
         0.9147,  0.1300, -0.4719,  0.4394, -0.2634, -0.6032,  0.5740, -1.0372,
        -0.5856, -0.2837,  0.2968, -0.3398,  1.0607, -0.0670,  0.1997, -0.1028],
       grad_fn=<SelectBackward>)
tensor([-0.0944, -0.2886, -0.3073,  0.0333,  0.4656,  0.1913, -0.2182,  0.4296,
        -0.2950,  0.2818, -0.3159,  0.4410,  0.0258,  0.1345, -0.1386, -0.2393,
        -0.1541, -0.2246,  0.3550, -0.1766, -0.0153, -0.2332, -0.2395, -0.1551,
         0.0719,  0.0951,  0.0354, -0.3901,  0.3507, -

THESE VALUES SHOULD BE DIFFERENT
tensor([-0.1370, -0.4188, -0.4459,  0.0483,  0.6758,  0.2776, -0.3167,  0.6235,
        -0.4281,  0.4090, -0.4585,  0.6400,  0.0375,  0.1952, -0.2011, -0.3472,
        -0.2236, -0.3259,  0.5152, -0.2563, -0.0222, -0.3384, -0.3476, -0.2251,
         0.1043,  0.1380,  0.0514, -0.5662,  0.5090, -1.0926,  0.3040,  1.4066,
         0.1902,  0.3010, -0.9314,  0.3816, -0.0229, -0.5982,  0.5892,  0.1747,
         0.0237,  0.7334,  0.6304, -0.8470,  0.6093, -0.7605,  0.3215,  0.2205,
         0.9147,  0.1300, -0.4719,  0.4394, -0.2634, -0.6032,  0.5740, -1.0372,
        -0.5856, -0.2837,  0.2968, -0.3398,  1.0607, -0.0670,  0.1997, -0.1028],
       grad_fn=<SelectBackward>)
tensor([-0.0944, -0.2886, -0.3073,  0.0333,  0.4656,  0.1913, -0.2182,  0.4296,
        -0.2950,  0.2818, -0.3159,  0.4410,  0.0258,  0.1345, -0.1386, -0.2393,
        -0.1541, -0.2246,  0.3550, -0.1766, -0.0153, -0.2332, -0.2395, -0.1551,
         0.0719,  0.0951,  0.0354, -0.3901,  0.3507, 