## Plot confusion matrices

In [ ]:
import os
import sys

# This should be '/home/croptype/bin/python'
print(sys.executable)

In [ ]:
import pandas as pd
import pickle
import numpy as np
import itertools
from matplotlib import pyplot as plt

import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [ ]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)

    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")

    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()

In [ ]:
classes = ['Grountnut', 'Maize', 'Rice', 'Soya Bean', 'Yam']

In [ ]:
# Plot best NN results for small

cm = np.asarray( [[ 903  114    5    2   17]
 [  20 1096    2   13    7]
 [   0    6 1029    0    0]
 [  37   15    4  936   46]
 [  19    0    2    3 1010]])
plt.figure()
plot_confusion_matrix(cm, classes, title='NN "small" train, acc = 94.10%')

cm = np.asarray([[256  67  55 191 592]
 [ 71 198  27 631 123]
 [ 93  83 366 222 263]
 [  8  17   0 385 635]
 [196  18  84 484 268]])
plt.figure()
plot_confusion_matrix(cm, classes, title='NN "small" val, acc = 27.62%')

cm = np.asarray([[137 532 100   8 252]
 [448 111 259   4 267]
 [317  54 435 228  77]
 [ 96  24 152 569 205]
 [ 89 165 149 153 480]])
plt.figure()
plot_confusion_matrix(cm, classes, title='NN "small" test, acc = 27.62%')

In [ ]:
# Plot best NN results for full

cm = np.asarray([[  7485,  64972,   1508,   1031,      0],
 [  6288, 230563,  13941,   7095,      0],
 [   565,  31271,  43142,     86,      0],
 [   479,  45156,    737,   7629,      0],
 [   429,  14170,   1256,    660,      0]])
plt.figure()
plot_confusion_matrix(cm, classes, title='NN "full" train, acc = 60.36%')

#cm = np.asarray([[  390  7119   192     7     0]
# [ 1129 27323  1886   505     0]
# [  501  3819  4109     0     0]
# [   51  5351    74   318     0]
# [    3  1975    98   107     0]])
#plt.figure()
#plot_confusion_matrix(cm, classes, title='NN "full" val, acc = 58.48%')

cm = np.asarray([[  537, 12054,   368,   143,     0],
 [ 1367, 29136,  2271,   929,     0],
 [    2,  4398,  6005,    10,     0],
 [  142,  6605,    13,   935,     0],
 [    5,  3100,     4,   284,     0]])
plt.figure()
plot_confusion_matrix(cm, classes, title='NN "full" test, acc = 58.48%')

In [ ]:
# Plot best CNN results for small

cm = np.asarray([[1041,    0,    0,    0,    0],
 [   0, 1138,    0,    0,    0],
 [   0,    0, 1035,    0,    0],
 [   0,    0,    0, 1038,    0],
 [   0,    0,    0,    0, 1034]])

plt.figure()
plot_confusion_matrix(cm, classes, title='CNN "small" train, acc = 100%')

cm = np.asarray([[671,  95,  40,  65, 290],
 [446, 252,   8, 176, 168],
 [164,  24, 101, 357, 381],
 [ 33, 129,  95, 313, 475],
 [ 87,  94,  19, 405, 445]])

plt.figure()
plot_confusion_matrix(cm, classes, title='CNN "small" val, acc = 33.41%')

cm = np.asarray([[267, 287,  44,  19, 412],
 [208, 160, 103, 113, 505],
 [343,   2, 254,  97, 415],
 [115,   8,  14, 553, 356],
 [ 72, 129,  58, 329, 448]])

plt.figure()
plot_confusion_matrix(cm, classes, title='CNN "small" test, acc = 33.41%')



In [ ]:
# Plot best CNN results for full

cm = np.asarray( [[ 22274,  47404,   3364,   1395,    559],
 [  7527, 231717,  11931,   5268,   1444],
 [  1541,  26602,  45862,    787,    272],
 [  1757,  34188,   1947,  15536,    573],
 [   709,   8889,    447,    647,   5823]])

plt.figure()
plot_confusion_matrix(cm, classes, title='CNN "full" train, acc = 67.13%')

#cm = np.asarray([[  537  6244   539   289    99]
# [ 1933 24078  2872  1424   536]
# [  462  4753  2946   147   121]
# [  366  4504   289   522   113]
# [  237  1556    82   142   166]])
#plt.figure()
#plot_confusion_matrix(cm, classes, title='CNN "full" val, acc = 51.40%')

cm = np.asarray([[ 1217, 10468,   957,   346,   114],
 [ 2433, 26126,  2991,  1407,   746],
 [  557,  5991,  3604,   220,    43],
 [  513,  5874,   495,   643,   170],
 [  213,  2444,   174,   233,   329]])

plt.figure()
plot_confusion_matrix(cm, classes, title='CNN "full" test, acc = 51.40%')

In [ ]:
# Plot best CNN results for full

cm = np.asarray( [[ 73787    994     55     79     81]
 [  1290 255628    438    388    143]
 [    79    608  74330     23     24]
 [   354   1209     34  52361     43]
 [   229    280     20     12  15974]])

plt.figure()
plot_confusion_matrix(cm, classes, title='CNN "full" train, acc = 98.67%')

cm = np.asarray([[ 1549  4882   834   312   131]
 [ 3664 21693  2532  2343   611]
 [  748  4026  3492   130    33]
 [  356  4072    73  1119   174]
 [  284  1452   124   139   184]])

plt.figure()
plot_confusion_matrix(cm, classes, title='CNN "full" val, acc = 51.02%')

cm = np.asarray([[ 2863  9068   422   575   174]
 [ 5504 21841  2166  3288   904]
 [  563  4033  5585   164    70]
 [  848  5342   101  1199   205]
 [  506  2279   112   240   256]])

plt.figure()
plot_confusion_matrix(cm, classes, title='CNN "full" val, acc = 51.02%')